Feat: export quinn connection metrics
8xFF/atm0s-small-p2p pull request #23
Opened 2024-11-21 04:38 UTC by marverlous811

2024-11-21 16:46 UTC, giangndm requested changes

2024-11-21 16:46 UTC, giangndm commented on src/peer/peer_internal.rs
> +pub struct PeerMetrics {
I think it should be PeerConnectionMetric

2024-11-22 02:38 UTC, marverlous811 commented
@giangndm I have resolved all your comments

2024-11-26 07:26 UTC, giangndm approved these changes

2024-11-26 07:28 UTC, merged